{{ if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "buildbuddy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
spec:
  {{ toYaml .Values.podDisruptionBudget.spec }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
{{ end }}
