{{ if and
  (.Values.ingress.enabled)
  (and
    (eq .Values.ingress.class "alb")
    (eq .Values.service.type "NodePort")
  )
}}
#######
# ALB #
#######
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "buildbuddy.fullname" . }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"

    alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
    alb.ingress.kubernetes.io/backend-protocol-version: "GRPC"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    {{- with .Values.ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.grpcHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "buildbuddy.name" . }}
            port:
              name: grpc
  tls:
    - secretName: {{ .Values.ingress.grpcHost }}-tls
      hosts:
        - {{ .Values.ingress.grpcHost }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "buildbuddy.fullname" . }}-at-grpc
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"

    alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
    alb.ingress.kubernetes.io/backend-protocol-version: "GRPC"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    {{- with .Values.ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "buildbuddy.name" . }}
                port:
                  name: grpc
  tls:
    - secretName: {{ .Values.ingress.grpcHost }}-tls
      hosts:
        - {{ .Values.ingress.grpcHost }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "buildbuddy.fullname" . }}-http
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"

    alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
    alb.ingress.kubernetes.io/backend-protocol-version: "HTTP1"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    {{- with .Values.ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.httpHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "buildbuddy.name" . }}
            port:
              name: http
  tls:
    - secretName: {{ .Values.ingress.httpHost }}-tls
      hosts:
        - {{ .Values.ingress.httpHost }}
{{ end }}
