{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildbuddy.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "buildbuddy.fullname" . }}-peer-discovery
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "buildbuddy.fullname" . }}-peer-discovery
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "buildbuddy.fullname" . }}-peer-discovery
subjects:
  - kind: ServiceAccount
    name: {{ include "buildbuddy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
