apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildbuddy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
data:
  redis-config-file: |
  {{- /* Make a deep copy of the default config */}}
  {{- $c := deepCopy .Values.config }}
  {{- /* maxMemory used to be a top level values option. If it's still being used copy it over to the config object. */ }}
  {{- if hasKey .Values "maxMemory" }}
    {{- $_ := set $c "maxmemory" .Values.maxMemory }}
  {{- end }}
{{- range $k, $v := $c }}
    {{ $k }} {{ $v }}
{{- end }}

