{{- if .Values.sharded }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "buildbuddy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "buildbuddy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
    {{- if .Values.extraPodLabels }}
    {{- .Values.extraPodLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "buildbuddy.fullname" . }}
  # This is a bit of a hack to limit the speed at which replicas are updated
  # to minimize impact on remote executions. When redis restarts, Bazel will retry
  # impacted actions but multiple redis restarts can prematurely exhaust Bazel retry
  # attempts.
  # The individual redis pods are accessed via a headless service that does not depend
  # on the readiness state of the pods.
  minReadySeconds: 3600
  template:
    metadata:
      annotations:
        {{- if .Values.extraPodAnnotations }}
        {{- .Values.extraPodAnnotations | toYaml | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "buildbuddy.chart" . }}
        {{- if .Values.extraPodLabels }}
        {{- .Values.extraPodLabels | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.nodeSelector}}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations}}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "{{ include "buildbuddy.name" . }}"
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - "{{ .Release.Name }}"
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command:
            - redis-server
            - "/redis-master/redis.conf"
          resources:
          {{- if .Values.resources }}
            {{- .Values.resources | toYaml | nindent 12 }}
          {{- end }}
          env:
          {{- if .Values.extraEnvVars }}
            {{- .Values.extraEnvVars | toYaml | nindent 10 }}
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.service.internalRedisPort }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - info
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
            {{- if .Values.extraVolumeMounts -}}
            {{ .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "buildbuddy.fullname" . }}-config
            items:
              - key: redis-config-file
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildbuddy.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: redis
      protocol: 'TCP'
      port: 6379
      targetPort: 6379
{{- end }}
