{
 "title": "BuildBuddy Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "window",
    "label": "Averaging Window",
    "query": "30s, 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 8h, 16h, 1d, 2d, 5d, 7d, 14d, 30d"
   },
   {
    "name": "job",
    "label": "Jobs",
    "query": "buildbuddy-enterprise, executor"
   }
  ]
 },
 "panels": [
  {
   "title": "System status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "${job} instances",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "repeat": "job",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(up{app_kubernetes_io_name=\"${job}\"})"
      }
     ]
    },
    {
     "title": "${job} instances",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(up{app_kubernetes_io_name=\"${job}\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations per second (by status)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (invocation_status) (rate(buildbuddy_invocation_count[${window}]))",
       "legendFormat": "{{invocation_status}}"
      }
     ]
    },
    {
     "title": "Median invocation duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_invocation_duration_usec_bucket[${window}])) by (le))"
      }
     ]
    },
    {
     "title": "Build events uploaded per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_invocation_build_event_count[${window}]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflows started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_webhook_handler_workflows_started[${window}]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total downloaded bytes per second",
     "type": "graph",
     "description": "Total number of bytes downloaded by consumers of the cache, per second. This does _not_ represent the average download speed across cache requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_download_size_bytes_sum[${window}]))"
      }
     ]
    },
    {
     "title": "Total uploaded bytes per second",
     "type": "graph",
     "description": "Total number of bytes uploaded by consumers of the cache, per second. This does _not_ represent the average upload speed across cache requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_upload_size_bytes_sum[${window}]))"
      }
     ]
    },
    {
     "title": "Action cache events per second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "repeat": "cache_type",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cache_event_type) (rate(buildbuddy_remote_cache_events{cache_type=\"action_cache\"}[${window}]))",
       "legendFormat": "{{cache_event_type}}"
      }
     ]
    },
    {
     "title": "CAS events per second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cache_event_type) (rate(buildbuddy_remote_cache_events{cache_type=\"cas\"}[${window}]))",
       "legendFormat": "{{cache_event_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fraction of working executors",
     "type": "graph",
     "description": "Chart is stacked, so values always add up to 100%.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "count(buildbuddy_remote_execution_tasks_executing > 0) / count(buildbuddy_remote_execution_tasks_executing)",
       "legendFormat": "Working"
      },
      {
       "expr": "1 - count(buildbuddy_remote_execution_tasks_executing > 0) / count(buildbuddy_remote_execution_tasks_executing)",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Executor autoscaling",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(buildbuddy_remote_execution_queue_length)",
       "legendFormat": "Avg executor queue length"
      },
      {
       "expr": "sum(up{app_kubernetes_io_name=\"executor\"})",
       "legendFormat": "Executor instances"
      }
     ]
    },
    {
     "title": "Median action stage durations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le, stage) (rate(buildbuddy_remote_execution_executed_action_metadata_durations_usec_bucket{stage!=\"worker\"}[${window}]))\n)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Avg resources allocated to tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(buildbuddy_remote_execution_assigned_milli_cpu{app_kubernetes_io_name=\"executor\", pod_name=~\"executor-.*\"}\n  / on (pod_name) (\n  label_replace(kube_pod_container_resource_limits_cpu_cores{pod=~\"executor-.*\"} * 1000, \"pod_name\", \"$1\", \"pod\", \"(.*)\")))",
       "legendFormat": "Avg CPU assigned"
      },
      {
       "expr": "avg(buildbuddy_remote_execution_assigned_ram_bytes{app_kubernetes_io_name=\"executor\", pod_name=~\"executor-.*\"}\n  / on (pod_name) (\n  label_replace(kube_pod_container_resource_limits_memory_bytes{pod=~\"executor-.*\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\")))",
       "legendFormat": "Avg RAM assigned"
      }
     ]
    },
    {
     "title": "Approx. total unclaimed tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_execution_queue_length) / 3"
      }
     ]
    },
    {
     "title": "Total uploaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_file_upload_size_bytes_sum[${window}]))"
      }
     ]
    },
    {
     "title": "Actions executed per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_count[${window}]))"
      }
     ]
    },
    {
     "title": "Remote executor instances",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(up{app_kubernetes_io_name=\"executor\"})"
      }
     ]
    },
    {
     "title": "Total downloaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_execution_file_download_size_bytes_sum[${window}]))"
      }
     ]
    },
    {
     "title": "Executor queue length by instance",
     "type": "graph",
     "description": "Number of actions waiting to be executed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, instance) (buildbuddy_remote_execution_queue_length{app_kubernetes_io_name=\"executor\"})",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Median executor queue length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quantile(0.5, buildbuddy_remote_execution_queue_length)"
      }
     ]
    },
    {
     "title": "Total CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"executor-dev\"}[${window}]))",
       "legendFormat": "CPU usage"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL queries per second (by query template)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (sql_query_template) (rate(buildbuddy_sql_query_count[${window}]))",
       "legendFormat": "{{sql_query_template}}"
      }
     ]
    },
    {
     "title": "Median SQL query duration by query template",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (sql_query_template, le) (rate(buildbuddy_sql_query_duration_usec_bucket[${window}]))\n)",
       "legendFormat": "{{sql_query_template}}"
      }
     ]
    },
    {
     "title": "SQL queries per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_sql_query_count[${window}]))"
      }
     ]
    },
    {
     "title": "SQL error rate (errors per second / queries per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_sql_error_count[${window}]))\n/ (sum(rate(buildbuddy_sql_query_count[${window}])))"
      }
     ]
    },
    {
     "title": "SQL errors per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_sql_error_count[${window}]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Blobstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_blobstore_read_size_bytes_sum[${window}]))"
      }
     ]
    },
    {
     "title": "Median download duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_blobstore_read_duration_usec_bucket[${window}])) by (le))"
      }
     ]
    },
    {
     "title": "Uploaded bytes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_blobstore_write_size_bytes_sum[${window}]))"
      }
     ]
    },
    {
     "title": "Median upload duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_blobstore_write_duration_usec_bucket[${window}])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 5xx error ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_http_request_handler_duration_usec_count{code=~\"5..\"}[${window}]))\n  /\nsum(rate(buildbuddy_http_request_handler_duration_usec_count[${window}]))",
       "legendFormat": "Error ratio"
      }
     ]
    },
    {
     "title": "HTTP requests per second by route",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (rate(buildbuddy_http_request_count[${window}]))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "HTTP requests per second by method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (rate(buildbuddy_http_request_count[${window}]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "HTTP responses per second by status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(buildbuddy_http_request_handler_duration_usec_count[${window}]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Median HTTP request handler duration (2xx responses only)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le, code) (rate(buildbuddy_http_request_handler_duration_usec_bucket{code=~\"2..\"}[${window}])))"
      }
     ]
    },
    {
     "title": "Median HTTP response size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(buildbuddy_http_response_size_bytes_bucket[${window}]))\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "golang (${job})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Heap size",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      },
      {}
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 165 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "GC CPU fraction",
     "type": "graph",
     "description": "% of time spent in the garbage collector since the program started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Median GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.5\",app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "golang (${job})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap size",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      },
      {}
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 165 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "GC CPU fraction",
     "type": "graph",
     "description": "% of time spent in the garbage collector since the program started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Median GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.5\",app_kubernetes_io_name=\"${job}\"}",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (${job})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Handled gRPC requests per second by status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{app_kubernetes_io_name=\"${job}\"}[${window}]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_method) (rate(grpc_server_handled_total{app_kubernetes_io_name=\"${job}\"}[${window}]))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (${job})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handled gRPC requests per second by status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{app_kubernetes_io_name=\"${job}\"}[${window}]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_method) (rate(grpc_server_handled_total{app_kubernetes_io_name=\"${job}\"}[${window}]))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Build event handler duration",
     "type": "graph",
     "description": "Measures the time spent handling build events. In a healthy state, this should be very small (on the order of microseconds) in most cases, since the build event handler needs to be very high throughput.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_build_event_handler_duration_usec_bucket[${window}])) by (le))",
       "legendFormat": "Median"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(buildbuddy_build_event_handler_duration_usec_bucket[${window}])) by (le))",
       "legendFormat": "90th %"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_build_event_handler_duration_usec_bucket[${window}])) by (le))",
       "legendFormat": "95th %"
      }
     ]
    }
   ]
  }
 ]
}