apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "buildbuddy.fullname" . }}-config
  labels:
    {{- include "buildbuddy.labels" . | nindent 4 }}
data:
  {{- /* Make a deep copy of the default config */}}
  {{- $c := deepCopy .Values.config }}

  {{- /* Update the copied default config based on .Values */}}

  {{- if and .Values.config.database.data_source .Values.mysql.enabled}}
  {{- $message := "Either enable mysql with mysql.enabled or configure a data_source in config, not both!\n\nconfig:\n  database:\n    data_source:: ..." }}
  {{- print "\n\nDIRECT CONFIGURATION NOT SUPPORTED:\n-----------------------------------\n\n" $message | fail }}
  {{- end }}

  {{- if .Values.mysql.enabled }}
  {{- $_ := set $c.database "data_source" (print "mysql://" .Values.mysql.mysqlUser ":" .Values.mysql.mysqlPassword "@tcp(" .Release.Name "-mysql:3306)/" .Values.mysql.mysqlDatabase) }}
  {{- else if not .Values.config.database.data_source }}
  {{- $_ := set $c.database "data_source" "sqlite3:///tmp/buildbuddy-enterprise.db" }}
  {{- end }}

  {{- /* Render the processed config as an encoded YAML string */}}
  {{- /* NOTE: Mounted at /config.yaml on the buildbuddy pod */}}
  config.yaml: {{ $c | toYaml | b64enc }}
