apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildbuddy.name" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "buildbuddy.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: 'TCP'
      port: {{ .Values.service.externalHTTPPort }}
      targetPort: {{ .Values.service.internalHTTPPort }}
    - name: grpc
      protocol: 'TCP'
      port: {{ .Values.service.externalGRPCPort }}
      targetPort: {{ .Values.service.internalGRPCPort }}
      {{- if ge .Capabilities.KubeVersion.Minor "20" }}
      appProtocol: kubernetes.io/h2c
      {{- end }}
    {{- if and .Values.service.externalHTTPSPort .Values.service.internalHTTPSPort }}
    - name: https
      protocol: 'TCP'
      port: {{ .Values.service.externalHTTPSPort }}
      targetPort: {{ .Values.service.internalHTTPSPort }}
    {{- end }}
    {{- if and .Values.service.externalGRPCSPort .Values.service.internalGRPCSPort }}
    - name: grpcs
      protocol: 'TCP'
      port: {{ .Values.service.externalGRPCSPort }}
      targetPort: {{ .Values.service.internalGRPCSPort }}
      {{- if ge .Capabilities.KubeVersion.Minor "20" }}
      appProtocol: kubernetes.io/h2c
      {{- end }}
    {{- end }}
    {{- if and .Values.service.externalMetricsPort .Values.service.internalMetricsPort }}
    - name: metrics
      protocol: 'TCP'
      port: {{ .Values.service.externalMetricsPort }}
      targetPort: {{ .Values.service.internalMetricsPort }}
    {{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
