## Default values for BuildBuddy.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## The Redis container image to use.
image:
  repository: redis
  tag: 5.0.4
  imagePullPolicy: IfNotPresent

# Whether to create a sharded deployment using a StatefulSet.
# If set to false, a single replica deployment is created.
# For most users a single replica Redis instance will be sufficient.
sharded: false
## The number of Redis shards (replicas) to run.
## Only used if "sharded" is set to true.
replicas: 3

## The nodeSelector used for placing pods in separate node pools/groups
# nodeSelector:
#   # GCP
#   cloud.google.com/gke-nodepool: my-redis-pool
#   # AWS
#   eks.amazonaws.com/nodegroup: my-redis-pool

## The taints to schedule pods on (useful for mixed architecture clusters)
# tolerations:
#   - effect: NoSchedule
#     key: hardware_requirements
#     operator: Equal
#     value: x86_64


# config specifies options to render in the redis configuration file.
# Additional options may be added, if needed.
config:
  ## Maximum memory redis will use, should be less than the kubernetes resource limits below.
  maxmemory: "5gb"
  maxmemory-policy: "allkeys-lru"

## The default resources to give redis.
resources:
  limits:
    cpu: "1"
    memory: "6Gi"
  requests:
    cpu: "1"
    memory: "5Gi"

## Exposes the Redis service via a service.
service:
  type: ClusterIP
  internalRedisPort: 6379

## Additional env vars
extraEnvVars: []

# Add additional volumes and mounts
extraVolumes: []
extraVolumeMounts: []
