## Default values for BuildBuddy.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## The BuildBuddy container image to use.
image:
  repository: redis
  tag: 5.0.4
  imagePullPolicy: IfNotPresent

## The number of app replicas to run.
## If setting this number higher than 1, make sure to configure a mysql database (not sqlite) and gcs storage
## so data can be shared across replicas.
## Using multiple replicas with a sqlite3 database or disk storage is not supported.
replicas: 1

## The nodeSelector used for placing pods in separate node pools/groups
# nodeSelector:
#   # GCP
#   cloud.google.com/gke-nodepool: my-redis-pool
#   # AWS
#   eks.amazonaws.com/nodegroup: my-redis-pool

## The taints to schedule pods on (useful for mixed architecture clusters)
# tolerations:
#   - effect: NoSchedule
#     key: hardware_requirements
#     operator: Equal
#     value: x86_64

## Maximum memory redis will use, should be less than the kubernetes resource limits below.
maxMemory: "5gb"

## The default resources to give redis.
resources:
  limits:
    cpu: "1"
    memory: "6Gi"
  requests:
    cpu: "1"
    memory: "5Gi"

## Exposes the Redis service via a LoadBalancer on the given ports.
service:
  type: ClusterIP
  internalRedisPort: 6379

## Additional env vars
extraEnvVars: []

# Add additional volumes and mounts
extraVolumes: []
extraVolumeMounts: []
