name: Lint Helm Charts
on:
  pull_request:

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs charts)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Add Helm repositories
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          find charts -name "requirements.yaml" -exec grep 'repository: https://' {} + | awk '{print $2}' | sort -u | while read -r repo; do
            repo_name=$(echo "$repo" | sed -e 's,https://,,; s,http://,,; s,/.*,,; s,\..*,,')
            helm repo add "$repo_name" "$repo"
          done

      - name: Build Helm dependencies
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          for chart in $(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs charts); do
            helm dependency build "$chart"
          done

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint-and-install \
             --check-version-increment=true \
             --target-branch ${{ github.event.repository.default_branch }} \
             --chart-dirs charts
